name: NIP Rent

on: [push]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    name: Test with pytest
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4 # Zmieniono na v4 (v6 jeszcze nie istnieje/nie jest stabilne)

    - name: Install UV
      uses: astral-sh/setup-uv@v3 # Stabilna wersja to v3
      with:
        enable-cache: true

    - name: Set up Python
      run: uv python install

    - name: Install the project
      run: uv sync --all-extras --dev

    - name: Run tests
      run: uv run pytest tests -v 

    - name: Run linter (code/src)
      run: uv run ruff check src --exit-zero

    - name: Run linter (main_demo.py)
      run: uv run ruff check main_demo.py --exit-zero
    
    - name: Generate Docs
      run: uv run pdoc src/ -o ./docs-output # Tutaj poprawiłem wcięcie (run musi być pod name)

    - name: Upload Artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './docs-output'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
      
